#!/usr/bin/env python3
r"""Resolved SED fitting demo: additive bulge + disk, ParrotEmulatorV2, real JWST PSFs.

A two-component galaxy (compact, old, quenched bulge + extended, young, dusty
star-forming disk at a common redshift) is rendered as a 10-band JWST/NIRCam
mock with the real trained ``ParrotEmulatorV2`` checkpoint and real JADES
empirical PSFs, noise is added, and the mock is fitted back **blind** -- the
injected truth is used only to generate the data and to grade the answer,
never to start the fit.

The model
---------
``AdditiveComponentModel`` (``src/arachne/spatial/additive.py``): light is
additive, so each component ``k`` has a unit-sum bivariate Gaussian
surface-brightness profile ``P_k(y, x)`` times the emulator SED ``F_k`` of
its *own* SPS parameters, including its own **total** stellar mass::

    I_b(y, x) = Σ_k F_kb(θ_k) · P_k(y, x)          (K emulator calls per likelihood)

which is then PSF-convolved per band.  ``theta`` is a flat float32 vector of
``K * (5 + 11) = 32`` numbers: per component ``[mu_y, mu_x, log_sigma_y,
log_sigma_x, atanh_rho, sps_raw (11)]`` with every SPS value mapped to its
emulator bounds by a sigmoid.  Redshift is *fixed* at the true value (a bulge
and disk of one galaxy share one redshift; fitting it is not the point here).

The prior is the model's own: uniform in physical space for every SPS
parameter (via the sigmoid Jacobian), the catalogue pipeline's default
Student-t(df=2, scale=0.3) on the ``logsfr_ratio_*`` (the emulator training
grid was drawn from it), Gaussians on the shape parameters.  The
``model_error_frac`` fractional floor in ``GaussianLikelihood`` (default 5%)
is added in quadrature to the photon noise: the emulator is only accurate to
a few per cent and a resolved fit sums ~2.5e5 pixels, so without the floor
the posterior would be far narrower than the emulator's own systematics.

The blind pipeline
------------------
1. ``blind_initial_theta``: centroid + rms size from the S/N-stacked image;
   two components on a size ladder (0.4x, 1.5x the moment size); generic
   neutral SPS values.
2. ``multistart_map``: ``find_map`` (Adam with the K masses re-solved by
   weighted linear least squares between rounds) from the neutral start and
   from a few generic archetypes (low/high dust, rising SFH); the best
   ``-log_posterior`` wins.  ``-log_post(MAP)`` is compared with
   ``-log_post(truth)`` *after* the fact, as a check that the true basin was
   found.
3. Sampling: ``--sampler nss`` (default) runs nested slice sampling from the
   prior (no starting point at all; also yields the evidence ``logZ``);
   ``--sampler nuts`` runs NUTS from the MAP.
4. Components are exchangeable; labels are broken by ordering by size
   (compact first) in the MAP and in every posterior sample.

Assumptions
-----------
* Pixel scale 0.03"/px (assumed; the JADES PSF FITS files carry no WCS).
  Only used for figure annotations -- the model works in pixels.
* Noise: Gaussian, per band, with sigma set so that the bulge-centre pixel
  has S/N = 30 in every band (``--noise-scale`` rescales it).  This is not
  a survey depth; it is chosen to make the disk outskirts a few-sigma per
  pixel.
* Truth: bulge total mass 10^10.3 Msun (sigma = 4 px), disk 10^10.6 Msun
  (16 x 10 px, rho = 0.35), co-centred at z = 2.

Known limitations
-----------------
* The mock is generated by the same emulator that fits it, so emulator
  systematics are absent from the data; the 5% floor is therefore a
  conservative choice here and the posterior is honest about photon noise
  only.  On real data emulator error dominates at this S/N.
* Photometry-only constraints on ``fesc_lya``, ``dust_bump_amplitude`` and
  the higher-order ``logsfr_ratio_*`` are weak; wide (prior-like) intervals
  there are the correct answer, not a failure.
* Two co-centred Gaussians is the mock's own family; real galaxies are not.

Usage
-----
    ssh gn004                     # needs a GPU node (see CLAUDE.md)
    python examples/demo_resolved_sed_fitting.py --quick        # smoke run
    python examples/demo_resolved_sed_fitting.py                # NSS, num_live=500
    python examples/demo_resolved_sed_fitting.py --sampler nuts --n-warmup 500 --n-samples 1000

Expected runtimes (H100, gn004; the blind MAP takes ~20-60 s of this)
---------------------------------------------------------------------
* ``--quick`` (num_live=100, 300 samples out):      ~12 min (measured, GPU shared)
* default (num_live=500, 1000 samples out):          ~20 min (measured, GPU alone; ESS ~640)
* ``--num-live 200``:                                ~15 min (interpolated)

Each NS step replaces ``num_live // 10`` points, so the number of steps is
nearly independent of ``num_live`` and the per-step cost grows sub-linearly
on a GPU (the replacements are vectorised); the evidence error scales as
``1/sqrt(num_live)``.  A second job sharing the GPU slows a run several-fold.

Outputs (under ``--outdir``, default ``outputs/demo/resolved_sed_fitting/``)
----------------------------------------------------------------------------
- ``truth.json``       injected truth (raw theta + physical parameters)
- ``map.json``         blind MAP (raw theta + physical parameters, -log_post)
- ``posterior.hdf5``   size-ordered posterior samples (+ logZ for NSS)
- ``figures/truth_model_residual_mosaic.png``
- ``figures/sps_param_maps.png``
- ``figures/sed_bulge_disk.png``
- ``figures/posterior_summary_1d.png``
- ``figures/sampler_diagnostics.png``
- ``figures/component_profiles.png``
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import sys
import time
from pathlib import Path

import equinox as eqx
import jax
import jax.numpy as jnp
import numpy as np

_ARACHNE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ARACHNE / "scripts"))

from fit_catalogue import PARAM_BOUNDS, SPS_PARAM_NAMES  # noqa: E402

from arachne.data.observation import ObservationCube  # noqa: E402
from arachne.data.psf import PSFModel  # noqa: E402
from arachne.emulator.base import SPSEmulator  # noqa: E402
from arachne.emulator.parrot_emulator_v2 import load_emulator  # noqa: E402
from arachne.forward_model.pipeline import ForwardModel  # noqa: E402
from arachne.inference.initialisation import (  # noqa: E402
    MAPResult,
    blind_initial_theta,
    multistart_map,
)
from arachne.inference.nss_sampler import NSSResult, NSSSampler  # noqa: E402
from arachne.inference.nuts_sampler import NUTSResult, NUTSSampler  # noqa: E402
from arachne.likelihood.gaussian import GaussianLikelihood  # noqa: E402
from arachne.priors.specs import (  # noqa: E402
    DEFAULT_PRIORS,
    build_component_log_prior,
    resolve_prior_specs,
)
from arachne.psf.convolution import PSFConvolver  # noqa: E402
from arachne.spatial.additive import AdditiveComponentModel  # noqa: E402

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

CHECKPOINT = _ARACHNE / "scripts/outputs/emulators/parrot_emulator_v2.eqx"
PSF_DIR = Path("/cosma/apps/dp276/dc-harv3/synference/priv/JADES-DR3-GS")
DEFAULT_OUTDIR = _ARACHNE / "outputs/demo/resolved_sed_fitting"

PIXEL_SCALE = 0.03  # arcsec/px, assumed -- see module docstring
NPIX = 160  # hard lower bound: real PSF kernel is 133x133 px
TRUE_REDSHIFT = 2.0
CENTER = float(NPIX // 2)
SNR_CENTRE = 30.0  # bulge-centre pixel S/N per band that sets the noise

# NIRCam wide+medium bands present in both the emulator checkpoint and PSF_DIR.
BAND_NAMES = [
    "JWST/NIRCam.F090W",
    "JWST/NIRCam.F115W",
    "JWST/NIRCam.F150W",
    "JWST/NIRCam.F200W",
    "JWST/NIRCam.F277W",
    "JWST/NIRCam.F335M",
    "JWST/NIRCam.F356W",
    "JWST/NIRCam.F410M",
    "JWST/NIRCam.F444W",
    "JWST/NIRCam.F480M",
]
REF_BAND = "JWST/NIRCam.F200W"  # band used for radial-profile figure
PIVOT_UM = {
    "F090W": 0.90, "F115W": 1.15, "F150W": 1.50, "F200W": 2.00, "F277W": 2.77,
    "F335M": 3.35, "F356W": 3.56, "F410M": 4.10, "F444W": 4.44, "F480M": 4.80,
}  # fmt: skip

PARAM_LABELS = {
    "log_mass": r"$\log M_\star / M_\odot$",
    "slope": r"$\delta$ (attenuation slope)",
    "fesc_lya": r"$f_\mathrm{esc,Ly\alpha}$",
    "dust_bump_amplitude": r"$B_{2175}$ (dust bump)",
    "log10metallicity": r"$\log Z$",
    "Av": r"$A_V$ (mag)",
    "logsfr_ratio_0": r"$\log \mathrm{SFR}_0/\mathrm{SFR}_1$",
    "logsfr_ratio_1": r"$\log \mathrm{SFR}_1/\mathrm{SFR}_2$",
    "logsfr_ratio_2": r"$\log \mathrm{SFR}_2/\mathrm{SFR}_3$",
    "logsfr_ratio_3": r"$\log \mathrm{SFR}_3/\mathrm{SFR}_4$",
    "logsfr_ratio_4": r"$\log \mathrm{SFR}_4/\mathrm{SFR}_5$",
}
MAP_FIGURE_PARAMS = ["log_mass", "Av", "log10metallicity", "logsfr_ratio_0"]
SHAPE_NAMES = ["mu_y [px]", "mu_x [px]", "sigma_y [px]", "sigma_x [px]", "rho"]
COMPONENT_NAMES = ["bulge (compact, comp 0)", "disk (extended, comp 1)"]

# Truth.  Masses are the TOTAL stellar mass of each component (the model's
# mass parameter is the component total, not a per-pixel surface density).
BULGE_PHYS = {
    "log_mass": 10.3,
    "slope": 0.5,
    "fesc_lya": 0.05,
    "dust_bump_amplitude": 0.2,
    "log10metallicity": -1.7,
    "Av": 0.15,
    "logsfr_ratio_0": 3.0,
    "logsfr_ratio_1": 1.5,
    "logsfr_ratio_2": 0.5,
    "logsfr_ratio_3": 0.0,
    "logsfr_ratio_4": 0.0,
}
BULGE_SHAPE = dict(sigma_y=4.0, sigma_x=4.0, rho=0.0)

DISK_PHYS = {
    "log_mass": 10.6,
    "slope": 0.0,
    "fesc_lya": 0.15,
    "dust_bump_amplitude": 1.5,
    "log10metallicity": -2.6,
    "Av": 1.8,
    "logsfr_ratio_0": -0.5,
    "logsfr_ratio_1": -0.3,
    "logsfr_ratio_2": 0.0,
    "logsfr_ratio_3": 0.2,
    "logsfr_ratio_4": 0.0,
}
DISK_SHAPE = dict(sigma_y=16.0, sigma_x=10.0, rho=0.35)

# Generic SPS archetypes for multistart_map.  These are NOT the truth values:
# they probe the dust/age degeneracy from both sides and a rising SFH.
ARCHETYPES = [{}, {"Av": 0.3}, {"Av": 2.0}, {"logsfr_ratio_0": 1.0}]

BULGE_PX = (NPIX // 2, NPIX // 2)
DISK_PX = (NPIX // 2, NPIX // 2 + 14)  # disk-dominated pixel, r = 14 px along +x


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def to_raw(phys: float, lo: float, hi: float) -> float:
    p = (phys - lo) / (hi - lo)
    return float(np.log(p / (1.0 - p)))


class BandSubsetEmulator(SPSEmulator):
    """Restrict an emulator's output to a subset of its bands (same inputs)."""

    inner: SPSEmulator
    _band_names: tuple[str, ...] = eqx.field(static=True)
    _band_idx: tuple[int, ...] = eqx.field(static=True)

    def __init__(self, inner: SPSEmulator, band_names: list[str]) -> None:
        missing = [b for b in band_names if b not in inner.band_names]
        if missing:
            raise ValueError(f"bands not in emulator: {missing}")
        self.inner = inner
        self._band_names = tuple(band_names)
        self._band_idx = tuple(inner.band_names.index(b) for b in band_names)

    @property
    def param_names(self) -> list[str]:
        return list(self.inner.param_names)

    @property
    def band_names(self) -> list[str]:
        return list(self._band_names)

    def predict(self, params: jnp.ndarray) -> jnp.ndarray:
        return self.inner.predict(params)[:, jnp.array(self._band_idx)]


def _psf_path(band_name: str) -> Path:
    return PSF_DIR / f"{band_name.split('.')[-1]}_psf_norm.fits"


def load_emulator_and_psf() -> tuple[SPSEmulator, PSFModel]:
    print(f"Loading emulator checkpoint: {CHECKPOINT}")
    emulator = BandSubsetEmulator(load_emulator(CHECKPOINT), BAND_NAMES)
    assert list(emulator.param_names) == SPS_PARAM_NAMES
    print(f"  {len(emulator.param_names)} emulator params, {len(emulator.band_names)} bands")
    missing = [b for b in BAND_NAMES if not _psf_path(b).exists()]
    if missing:
        raise FileNotFoundError(f"Missing PSF files for {missing} under {PSF_DIR}")
    psf_model = PSFModel.from_fits({b: _psf_path(b) for b in BAND_NAMES})
    print(f"  Loaded {psf_model.n_bands} PSF kernels from {PSF_DIR}")
    return emulator, psf_model


def build_spatial_model(emulator: SPSEmulator) -> AdditiveComponentModel:
    names = list(emulator.param_names)
    free = [p for p in names if p != "redshift"]
    specs = resolve_prior_specs(free, None, PARAM_BOUNDS)  # DEFAULT_PRIORS resolved
    assert all(specs[p] == DEFAULT_PRIORS.get(p, {"dist": "uniform"}) for p in free)
    sps_log_prior = build_component_log_prior(
        names, specs, PARAM_BOUNDS, shared_param_names=[], fixed_param_names=["redshift"]
    )
    return AdditiveComponentModel(
        n_components=2,
        emulator_param_names=names,
        param_bounds=PARAM_BOUNDS,
        image_shape=(NPIX, NPIX),
        fixed_params={"redshift": TRUE_REDSHIFT},
        mass_param="log_mass",
        sps_log_prior=sps_log_prior,
    )


# ---------------------------------------------------------------------------
# Truth and mock observation
# ---------------------------------------------------------------------------


def build_truth_theta(model: AdditiveComponentModel) -> np.ndarray:
    blocks = []
    for phys, shape in ((BULGE_PHYS, BULGE_SHAPE), (DISK_PHYS, DISK_SHAPE)):
        raw = [to_raw(phys[p], *model.param_bounds[p]) for p in model.sps_param_names]
        blocks.append(
            [
                CENTER,
                CENTER,
                np.log(shape["sigma_y"]),
                np.log(shape["sigma_x"]),
                np.arctanh(shape["rho"]),
                *raw,
            ]
        )
    theta = model.join_theta(jnp.array(blocks, dtype=jnp.float32), jnp.zeros(model.n_shared))
    return np.asarray(theta, dtype=np.float32)


def synthesise_truth_image(
    model: AdditiveComponentModel, emulator: SPSEmulator, convolver: PSFConvolver, theta_true
) -> np.ndarray:
    img = convolver(model.model_image(jnp.asarray(theta_true), emulator, (NPIX, NPIX)))
    return np.asarray(img, dtype=np.float32)


def add_noise(
    true_image: np.ndarray, seed: int, noise_scale: float
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Per-band Gaussian noise with sigma_b = truth(bulge centre)_b / SNR_CENTRE."""
    rng = np.random.default_rng(seed)
    sigma = true_image[:, BULGE_PX[0], BULGE_PX[1]] / SNR_CENTRE * noise_scale
    noise = rng.normal(0.0, 1.0, size=true_image.shape).astype(np.float32) * sigma[:, None, None]
    variance = np.broadcast_to(sigma[:, None, None] ** 2, true_image.shape)
    return (true_image + noise).astype(np.float32), variance.astype(np.float32), sigma


def print_noise_summary(true_image: np.ndarray, sigma: np.ndarray) -> None:
    print("\n--- Mock noise summary ---")
    print(f"  sigma set so the bulge-centre pixel has S/N = {SNR_CENTRE:.0f} in every band")
    print(f"  {'band':22s} {'sigma[nJy]':>10s} {'S/N centre':>10s} {'S/N r=14px':>10s} "
          f"{'S/N total':>10s} {'N(S/N>3)':>9s}")  # fmt: skip
    npix = true_image[0].size
    for b, band in enumerate(BAND_NAMES):
        img = true_image[b]
        sn_tot = img.sum() / (sigma[b] * np.sqrt(npix))
        n3 = int((img / sigma[b] > 3).sum())
        print(
            f"  {band:22s} {sigma[b]:10.2f} {img[BULGE_PX] / sigma[b]:10.1f} "
            f"{img[DISK_PX] / sigma[b]:10.2f} {sn_tot:10.0f} {n3:9d}"
        )
    b = BAND_NAMES.index(REF_BAND)
    print(
        f"  {REF_BAND}: truth flux at centre {true_image[b][BULGE_PX]:.1f}, r=14px "
        f"{true_image[b][DISK_PX]:.2f}, r=40px {true_image[b][NPIX // 2, NPIX // 2 + 40]:.3f}, "
        f"corner {true_image[b][0, 0]:.4f} nJy"
    )


def build_forward_model(
    obs: ObservationCube,
    model: AdditiveComponentModel,
    emulator: SPSEmulator,
    convolver: PSFConvolver,
    model_err_frac: float,
) -> ForwardModel:
    obs_jax = obs.to_jax()
    likelihood = GaussianLikelihood(obs_jax, model_error_frac=model_err_frac)
    return ForwardModel(
        observation=obs_jax,
        spatial_model=model,
        emulator=emulator,
        convolver=convolver,
        likelihood=likelihood,
    )


# ---------------------------------------------------------------------------
# Blind fit
# ---------------------------------------------------------------------------


def run_blind_map(fwd: ForwardModel, quick: bool) -> MAPResult:
    """Blind MAP: data -> image moments -> neutral start -> multistart Adam.

    This function receives ONLY the forward model (which holds the noisy
    observation).  The injected truth is not an argument and is not used
    anywhere in the initialisation or optimisation.
    """
    print("\n--- Blind initialisation + MAP ---")
    t0 = time.perf_counter()
    theta0 = blind_initial_theta(fwd.spatial_model, fwd.observation)
    blocks, _ = fwd.spatial_model.split_theta(theta0)
    mu0 = np.asarray(blocks[:, :2], dtype=np.float64).round(2).tolist()
    sig0 = np.exp(np.asarray(blocks[:, 2:4], dtype=np.float64)).round(2).tolist()
    print(f"  moments start: centres {mu0}, sigmas {sig0} px")
    print(f"  -log_post(blind start, masses unsolved) = {-float(fwd.log_posterior(theta0)):.1f}")
    kwargs = dict(n_rounds=2, steps_per_round=150, final_steps=200) if quick else {}
    print(f"  multistart_map over {len(ARCHETYPES)} archetypes {ARCHETYPES} ...")
    res = multistart_map(fwd, theta0, ARCHETYPES, **kwargs)
    print(
        f"  blind MAP: -log_post = {res.neg_log_posterior:.1f} after {res.n_steps} Adam steps "
        f"per start  [{time.perf_counter() - t0:.0f}s]"
    )
    return res


def run_sampler(fwd: ForwardModel, theta_map: jnp.ndarray, args) -> NUTSResult:
    key = jax.random.PRNGKey(args.seed + 1)
    t0 = time.perf_counter()
    if args.sampler == "nss":
        num_live = 100 if args.quick else args.num_live
        n_out = min(args.n_samples, 300) if args.quick else args.n_samples
        print(
            f"\n--- Nested slice sampling: num_live={num_live}, "
            f"num_inner_steps={args.num_inner_steps or 3 * fwd.spatial_model.n_params}, "
            f"termination={args.termination:g}, n_samples_out={n_out} ---"
        )
        print("  (live points are drawn from the prior; the MAP is not used to start NSS)")
        sampler = NSSSampler(
            fwd,
            num_live=num_live,
            num_inner_steps=args.num_inner_steps,
            termination=args.termination,
            n_samples_out=n_out,
        )
        result = sampler.run(key)
        print(
            f"  logZ = {result.logZ:.2f} +/- {result.logZ_err:.2f}   ESS = {result.ess:.0f}   "
            f"n_steps = {result.n_steps}   n_dead = {result.n_dead}   "
            f"[{time.perf_counter() - t0:.0f}s]"
        )
    else:
        n_warmup = 100 if args.quick else args.n_warmup
        n_samples = 200 if args.quick else args.n_samples
        print(f"\n--- NUTS from the blind MAP: {n_warmup} warmup + {n_samples} samples ---")
        sampler = NUTSSampler(fwd, n_warmup=n_warmup, n_samples=n_samples, max_num_doublings=10)
        result = sampler.run(theta_map, key)
        infos = result.infos
        samples = np.asarray(result.samples)
        moved = float(np.mean(samples.std(axis=0) > 0))
        n_div = int(np.sum(np.asarray(infos.is_divergent)))
        depth = float(np.mean(np.asarray(infos.num_trajectory_expansions)))
        nsteps = float(np.mean(np.asarray(infos.num_integration_steps)))
        print(
            f"  acceptance = {result.acceptance_rate:.3f}   mean tree depth = {depth:.1f} "
            f"(mean {nsteps:.0f} leapfrog steps)   divergences = {n_div}   "
            f"fraction of dims that moved = {moved:.2f}   [{time.perf_counter() - t0:.0f}s]"
        )
    return result


# ---------------------------------------------------------------------------
# Recovery report
# ---------------------------------------------------------------------------


def decode_components(model: AdditiveComponentModel, thetas: jnp.ndarray) -> dict[str, np.ndarray]:
    """thetas (n, n_params) -> dict of physical per-component arrays.

    ``sps`` (n, K, N_free) holds the per-component free SPS parameters in
    ``model.sps_param_names`` order; ``shape`` (n, K, 5) holds
    ``[mu_y, mu_x, sigma_y, sigma_x, rho]``.
    """
    free_cols = jnp.array([model.emulator_param_names.index(p) for p in model.sps_param_names])

    def one(theta):
        mu, sigma, rho, sps_full = model.component_params(theta)
        shape = jnp.concatenate([mu, sigma, rho[:, None]], axis=1)
        return sps_full[:, free_cols], shape

    sps, shape = jax.vmap(one)(jnp.atleast_2d(thetas))
    return {"sps": np.asarray(sps), "shape": np.asarray(shape)}


def _interval_row(samples_1d: np.ndarray, truth: float) -> tuple[str, bool, bool]:
    q2, q16, q50, q84, q97 = np.percentile(samples_1d, [2.5, 16, 50, 84, 97.5])
    in68 = q16 <= truth <= q84
    in95 = q2 <= truth <= q97
    half = max(0.5 * (q84 - q16), 1e-12)
    dev = abs(q50 - truth) / half
    row = (
        f"truth={truth:8.3f}  median={q50:8.3f}  [{q16:8.3f},{q84:8.3f}]  "
        f"in68={'yes' if in68 else ' no'}  |med-truth|/halfwidth={dev:6.2f}"
    )
    return row, in68, in95


def report_recovery(
    model: AdditiveComponentModel,
    samples_ordered: jnp.ndarray,
    theta_true: np.ndarray,
    theta_map: jnp.ndarray,
) -> dict[str, np.ndarray]:
    print("\n=== Posterior recovery (truth used for grading only) ===")
    post = decode_components(model, samples_ordered)
    tru = decode_components(model, jnp.asarray(theta_true)[None])
    mapd = decode_components(model, jnp.asarray(theta_map)[None])
    names = model.sps_param_names
    n68 = n95 = n_tot = 0
    s68 = s95 = s_tot = 0
    for k, cname in enumerate(COMPONENT_NAMES):
        print(f"\n  {cname}:")
        for j, pname in enumerate(names):
            row, in68, in95 = _interval_row(post["sps"][:, k, j], float(tru["sps"][0, k, j]))
            print(f"    {pname:20s} {row}  MAP={mapd['sps'][0, k, j]:8.3f}")
            n68 += in68
            n95 += in95
            n_tot += 1
        for j, sname in enumerate(SHAPE_NAMES):
            row, in68, in95 = _interval_row(post["shape"][:, k, j], float(tru["shape"][0, k, j]))
            print(f"    {sname:20s} {row}  MAP={mapd['shape'][0, k, j]:8.3f}")
            s68 += in68
            s95 += in95
            s_tot += 1

    mi = model.mass_index
    tot = np.log10(np.sum(10.0 ** post["sps"][:, :, mi], axis=1))
    tot_true = float(np.log10(np.sum(10.0 ** tru["sps"][0, :, mi])))
    row, _, _ = _interval_row(tot, tot_true)
    print(f"\n  total stellar mass  log10 M_tot  {row}")

    print(
        f"\n  Summary: SPS parameters   truth inside 68% interval: {n68}/{n_tot}   "
        f"inside 95%: {n95}/{n_tot}"
    )
    print(
        f"           shape parameters truth inside 68% interval: {s68}/{s_tot}   "
        f"inside 95%: {s95}/{s_tot}"
    )
    print(
        "  Note: with 10-band photometry alone, fesc_lya, dust_bump_amplitude and the "
        "higher-order logsfr_ratio_* are weakly constrained, so wide intervals there are "
        "correct behaviour."
    )
    return {"post": post, "truth": tru, "map": mapd}


def reduced_chi2(fwd: ForwardModel, theta, variance: np.ndarray) -> float:
    """Noise-only reduced chi2 of the PSF-convolved model at theta."""
    model_img = np.asarray(fwd._model_image(jnp.asarray(theta, dtype=jnp.float32)))
    obs = np.asarray(fwd.observation.flux)
    chi2 = np.sum((obs - model_img) ** 2 / variance)
    return float(chi2 / (obs.size - fwd.spatial_model.n_params))


# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------


def _setup_mpl():
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    return plt


def plot_truth_model_residual(plt, figdir, true_image, obs_flux, obs_variance, model_image):
    nb = len(BAND_NAMES)
    fig, axes = plt.subplots(3, nb, figsize=(2.2 * nb, 6.6))
    for b, band in enumerate(BAND_NAMES):
        scale = max(true_image[b].max() / 50.0, 1e-3)
        vmax = np.arcsinh(true_image[b].max() / scale)
        for r, (img, lab) in enumerate(
            ((true_image[b], "Truth (noiseless)"), (model_image[b], "Recovered (median)"))
        ):
            ax = axes[r, b]
            ax.imshow(np.arcsinh(img / scale), origin="lower", cmap="viridis", vmin=0, vmax=vmax)
            ax.set_xticks([])
            ax.set_yticks([])
            if b == 0:
                ax.set_ylabel(lab, fontsize=9)
        axes[0, b].set_title(band.split(".")[-1], fontsize=9)
        chi = (obs_flux[b] - model_image[b]) / np.sqrt(obs_variance[b])
        ax = axes[2, b]
        ax.imshow(chi, origin="lower", cmap="RdBu_r", vmin=-3, vmax=3)
        ax.set_xticks([])
        ax.set_yticks([])
        if b == 0:
            ax.set_ylabel(r"$\chi$ = (obs - model)/$\sigma$", fontsize=9)
    fig.suptitle("Truth vs recovered model vs residual, per band (arcsinh stretch)", fontsize=12)
    fig.tight_layout()
    path = figdir / "truth_model_residual_mosaic.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"  Saved {path}")


def plot_sps_param_maps(plt, figdir, model, result, theta_true):
    names = model.sps_param_names
    truth_map = np.asarray(model.decode(jnp.asarray(theta_true), (NPIX, NPIX)))
    truth_map = truth_map.reshape(NPIX, NPIX, len(names))
    pct_maps = result.get_parameter_map((NPIX, NPIX), percentiles=[16, 50, 84])
    log_sigma_true = truth_map[:, :, model.mass_index]
    shown = log_sigma_true > log_sigma_true.max() - 3.5  # hide meaningless outskirts

    n_p = len(MAP_FIGURE_PARAMS)
    fig, axes = plt.subplots(n_p, 3, figsize=(9.5, 2.8 * n_p))
    for i, pname in enumerate(MAP_FIGURE_PARAMS):
        j = names.index(pname)
        truth_2d = np.where(shown, truth_map[:, :, j], np.nan)
        lo16, med, hi84 = (np.where(shown, np.asarray(m), np.nan) for m in pct_maps[pname])
        vmin, vmax = np.nanmin(truth_2d), np.nanmax(truth_2d)
        if pname == "log_mass":
            ylabel = r"$\log_{10}\,\Sigma_\star$ [$M_\odot$/px]"
        else:
            ylabel = "mass-weighted " + PARAM_LABELS[pname]
        for c, (img, title, cmap, kw) in enumerate(
            (
                (truth_2d, "Truth", "magma", dict(vmin=vmin, vmax=vmax)),
                (med, "Recovered median", "magma", dict(vmin=vmin, vmax=vmax)),
                ((hi84 - lo16) / 2, r"Recovered $\sigma$ (68% CI / 2)", "cividis", {}),
            )
        ):
            ax = axes[i, c]
            im = ax.imshow(img, origin="lower", cmap=cmap, **kw)
            ax.set_xticks([])
            ax.set_yticks([])
            fig.colorbar(im, ax=ax, fraction=0.046, pad=0.02)
            if i == 0:
                ax.set_title(title, fontsize=10)
        axes[i, 0].set_ylabel(ylabel, fontsize=9)
    fig.suptitle(
        "Summary maps from decode(): log stellar-mass surface density and\n"
        "mass-weighted component parameters (shown where $\\Sigma_\\star$ > peak - 3.5 dex)",
        fontsize=11,
    )
    fig.tight_layout()
    path = figdir / "sps_param_maps.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"  Saved {path}")


def plot_sed_bulge_disk(plt, figdir, fwd, true_image, obs_flux, obs_variance, model_image, samples):
    wl = np.array([PIVOT_UM[b.split(".")[-1]] for b in BAND_NAMES])
    pix = [BULGE_PX, DISK_PX]
    ys = jnp.array([p[0] for p in pix])
    xs = jnp.array([p[1] for p in pix])
    sub = samples[:: max(1, samples.shape[0] // 100)][:100]
    sed_samples = np.asarray(
        jax.lax.map(lambda t: fwd._model_image(t)[:, ys, xs], sub)
    )  # (n, N_bands, 2)

    fig, axes = plt.subplots(1, 2, figsize=(11, 4.2))
    for i, (ax, px, title) in enumerate(
        zip(axes, pix, ["Bulge centre pixel", "Disk pixel (r = 14 px)"])
    ):
        lo, hi = np.percentile(sed_samples[:, :, i], [16, 84], axis=0)
        ax.fill_between(wl, lo, hi, color="tab:red", alpha=0.25, label="Posterior 16-84%")
        ax.plot(wl, true_image[:, px[0], px[1]], "k-", label="Truth (noiseless)", zorder=2)
        ax.errorbar(
            wl,
            obs_flux[:, px[0], px[1]],
            yerr=np.sqrt(obs_variance[:, px[0], px[1]]),
            fmt="o",
            color="tab:gray",
            label="Noisy observed",
            alpha=0.8,
        )
        ax.plot(wl, model_image[:, px[0], px[1]], "o-", color="tab:red", label="Recovered (median)")
        ax.set_xlabel(r"Pivot wavelength [$\mu$m]")
        ax.set_ylabel("Flux [nJy / px]")
        ax.set_title(title)
        ax.legend(fontsize=8)
    fig.suptitle("Per-pixel SEDs: truth vs observed vs recovered", fontsize=12)
    fig.tight_layout()
    path = figdir / "sed_bulge_disk.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"  Saved {path}")


def plot_posterior_summary_1d(plt, figdir, model, dec):
    names = model.sps_param_names
    post, tru, mapd = dec["post"]["sps"], dec["truth"]["sps"], dec["map"]["sps"]
    fig, axes = plt.subplots(2, len(names), figsize=(2.0 * len(names), 4.8))
    for k in range(2):
        for j, pname in enumerate(names):
            ax = axes[k, j]
            ax.hist(post[:, k, j], bins=30, color="tab:blue", alpha=0.7)
            ax.axvline(tru[0, k, j], color="k", linestyle="--", linewidth=1, label="truth")
            ax.axvline(mapd[0, k, j], color="tab:red", linestyle=":", linewidth=1, label="MAP")
            ax.set_yticks([])
            ax.tick_params(labelsize=6)
            if k == 1:
                ax.set_xlabel(pname, fontsize=6, rotation=45, ha="right")
            if j == 0:
                ax.set_ylabel(COMPONENT_NAMES[k].split(" ")[0], fontsize=8)
    axes[0, 0].legend(fontsize=6)
    fig.suptitle(
        "Posterior SPS parameters per component (dashed = truth, dotted = blind MAP)", fontsize=11
    )
    fig.tight_layout()
    path = figdir / "posterior_summary_1d.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"  Saved {path}")


def plot_sampler_diagnostics(plt, figdir, result, sampler_name):
    path = figdir / "sampler_diagnostics.png"
    if sampler_name == "nss" and result.infos is not None:
        parts = result.infos.particles
        logl = np.asarray(parts.loglikelihood)
        it = np.arange(logl.size)
        fig, axes = plt.subplots(2, 1, figsize=(8, 5.5), sharex=True)
        axes[0].plot(it, logl, linewidth=0.6)
        axes[0].set_ylabel("log L of dead point")
        lo = np.percentile(logl, 5)
        axes[0].set_ylim(lo, logl.max() + 0.05 * (logl.max() - lo))
        if result.log_weights is not None:
            lw = np.asarray(result.log_weights)
            axes[1].plot(it[: lw.size], np.exp(lw - lw.max()), linewidth=0.6, color="tab:orange")
            axes[1].set_ylabel("posterior weight (rel.)")
        axes[1].set_xlabel("dead-point index (nested-sampling iteration)")
        fig.suptitle(
            f"NSS: logZ = {result.logZ:.2f} +/- {result.logZ_err:.2f}, ESS = {result.ess:.0f}, "
            f"{result.n_steps} steps",
            fontsize=11,
        )
    else:
        samples = np.asarray(result.samples)
        dims = [0, 2, 5, 16 + 5]  # bulge mu_y, bulge log_sigma_y, bulge mass raw, disk mass raw
        dims = [d for d in dims if d < samples.shape[1]]
        fig, axes = plt.subplots(len(dims) + 1, 1, figsize=(8, 1.6 * (len(dims) + 1)), sharex=True)
        for ax, d in zip(axes, dims):
            ax.plot(samples[:, d], linewidth=0.5)
            ax.set_ylabel(f"theta[{d}]", fontsize=8)
        acc = getattr(result.infos, "acceptance_rate", None)
        if acc is not None:
            axes[-1].plot(np.asarray(acc), linewidth=0.5, color="tab:orange")
            axes[-1].set_ylabel("accept rate", fontsize=8)
            axes[-1].set_ylim(0, 1)
        axes[-1].set_xlabel("sample")
        fig.suptitle("NUTS trace diagnostics", fontsize=11)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"  Saved {path}")


def _radial_profile(img: np.ndarray, centre: tuple[float, float], nbins: int = 40):
    yy, xx = np.mgrid[:NPIX, :NPIX]
    r = np.hypot(yy - centre[0], xx - centre[1]).ravel()
    edges = np.linspace(0, NPIX / 2, nbins + 1)
    idx = np.digitize(r, edges) - 1
    ok = (idx >= 0) & (idx < nbins)
    vals = img.ravel()
    mean = np.array([vals[ok & (idx == i)].mean() for i in range(nbins)])
    count = np.array([(ok & (idx == i)).sum() for i in range(nbins)])
    return 0.5 * (edges[1:] + edges[:-1]), mean, count


def plot_component_profiles(plt, figdir, fwd, model, emulator, theta_true, theta_map, sigma):
    b = BAND_NAMES.index(REF_BAND)
    fig, ax = plt.subplots(figsize=(7.5, 5))
    obs = np.asarray(fwd.observation.flux[b])
    mu_true = np.asarray(model.component_params(jnp.asarray(theta_true))[0])
    centre = (float(mu_true[0, 0]), float(mu_true[0, 1]))
    for theta, ls, lab in ((theta_true, "-", "truth"), (theta_map, "--", "blind MAP")):
        th = jnp.asarray(theta, dtype=jnp.float32)
        profiles = np.asarray(model.profiles(th))  # (K, H, W)
        seds = np.asarray(model.component_seds(th, emulator))  # (K, N_bands)
        for k, (cname, col) in enumerate(zip(["bulge", "disk"], ["tab:orange", "tab:blue"])):
            r, p, _ = _radial_profile(seds[k, b] * profiles[k], centre)
            ax.plot(r, p, ls, color=col, label=f"{cname} ({lab}, unconvolved)")
        r, p, _ = _radial_profile(np.asarray(fwd._model_image(th)[b]), centre)
        ax.plot(r, p, ls, color="k", label=f"total, PSF-convolved ({lab})")
    r, p, n = _radial_profile(obs, centre)
    ax.errorbar(r, p, yerr=sigma[b] / np.sqrt(n), fmt="o", ms=3, color="tab:gray", label="data")
    ax.set_yscale("log")
    peak = float(np.max(np.asarray(fwd._model_image(jnp.asarray(theta_true))[b])))
    ax.set_ylim(sigma[b] / 100, 30 * peak)
    ax.axhline(sigma[b], color="tab:gray", linestyle=":", linewidth=1)
    ax.text(NPIX / 2 * 0.98, sigma[b] * 1.15, r"1$\sigma$ per pixel", ha="right", fontsize=8)
    ax.set_xlabel(f'radius from bulge centre [px]  (1 px = {PIXEL_SCALE}" assumed)')
    ax.set_ylabel(f"{REF_BAND.split('.')[-1]} surface brightness [nJy / px]")
    ax.set_title("Component radial profiles (azimuthal mean)")
    ax.legend(fontsize=7, ncol=2)
    fig.tight_layout()
    path = figdir / "component_profiles.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"  Saved {path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def _phys_record(model: AdditiveComponentModel, theta) -> dict:
    d = decode_components(model, jnp.asarray(theta)[None])
    out = {}
    for k, cname in enumerate(["bulge", "disk"]):
        out[cname] = {p: float(d["sps"][0, k, j]) for j, p in enumerate(model.sps_param_names)}
        out[cname + "_shape"] = {n: float(d["shape"][0, k, j]) for j, n in enumerate(SHAPE_NAMES)}
    return out


def parse_args():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--outdir", type=Path, default=DEFAULT_OUTDIR)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument(
        "--quick", action="store_true", help="small smoke run (num_live 100, fewer steps)"
    )
    parser.add_argument(
        "--noise-scale", type=float, default=1.0, help="multiply the S/N=30 noise sigma"
    )
    parser.add_argument(
        "--model-err-frac", type=float, default=0.05, help="fractional model-error floor"
    )
    parser.add_argument("--sampler", choices=["nss", "nuts"], default="nss")
    parser.add_argument("--num-live", type=int, default=500, help="NSS live points")
    parser.add_argument(
        "--num-inner-steps", type=int, default=None, help="NSS slice steps (default 3*n_params)"
    )
    parser.add_argument(
        "--termination", type=float, default=1e-3, help="NSS stop when logZ_live-logZ < this"
    )
    parser.add_argument("--n-warmup", type=int, default=500, help="NUTS warmup steps")
    parser.add_argument(
        "--n-samples", type=int, default=1000, help="NUTS samples / NSS equal-weight samples out"
    )
    return parser.parse_args()


def main():
    args = parse_args()
    outdir: Path = args.outdir
    figdir = outdir / "figures"
    figdir.mkdir(parents=True, exist_ok=True)
    print(f"JAX backend: {jax.default_backend()}   devices: {jax.devices()}")
    if jax.default_backend() == "cpu":
        print("  WARNING: running on CPU; this demo is meant for a GPU node (see docstring).")
    t_start = time.perf_counter()

    emulator, psf_model = load_emulator_and_psf()
    model = build_spatial_model(emulator)
    convolver = PSFConvolver(psf_model, image_shape=(NPIX, NPIX))
    print(
        f"Spatial model: AdditiveComponentModel K=2, {model.n_params} free params "
        f"({model.n_params_per_component} per component), fixed {model.fixed_params}"
    )

    # ---- truth + mock (the ONLY place theta_true enters the data path) ----
    theta_true = build_truth_theta(model)
    true_image = synthesise_truth_image(model, emulator, convolver, theta_true)
    assert np.all(np.isfinite(true_image)) and true_image.max() > 0
    # FFT convolution leaves ~1e-7 relative roundoff (tiny negatives) in empty corners.
    assert true_image.min() > -1e-4 * true_image.max(), true_image.min()
    flux_noisy, variance, sigma = add_noise(true_image, args.seed, args.noise_scale)
    print_noise_summary(true_image, sigma)
    with open(outdir / "truth.json", "w") as f:
        json.dump(
            {
                "theta_true": theta_true.tolist(),
                "theta_layout": "per component [mu_y, mu_x, log_sigma_y, log_sigma_x, "
                "atanh_rho, sps_raw...]; sps in sps_param_names order",
                "sps_param_names": model.sps_param_names,
                "bulge": BULGE_PHYS,
                "bulge_shape": BULGE_SHAPE,
                "disk": DISK_PHYS,
                "disk_shape": DISK_SHAPE,
                "log_mass_is_component_total": True,
                "redshift": TRUE_REDSHIFT,
                "pixel_scale_arcsec": PIXEL_SCALE,
                "npix": NPIX,
                "band_names": BAND_NAMES,
                "noise_sigma_nJy": sigma.tolist(),
                "snr_centre": SNR_CENTRE * 1.0 / args.noise_scale,
                "model_err_frac": args.model_err_frac,
                "seed": args.seed,
            },
            f,
            indent=2,
        )

    obs = ObservationCube(
        flux=flux_noisy,
        variance=variance,
        mask=np.ones_like(flux_noisy),
        band_names=BAND_NAMES,
        pixel_scale=PIXEL_SCALE,
    )
    fwd = build_forward_model(obs, model, emulator, convolver, args.model_err_frac)
    print(f"Likelihood: Gaussian with model_error_frac = {args.model_err_frac}")

    # ---- blind fit: no truth information from here until the report ----
    map_res = run_blind_map(fwd, args.quick)
    theta_map = map_res.theta
    # Truth-based grading of the MAP (reporting only; the fit is already done).
    nlp_true = -float(fwd.log_posterior(jnp.asarray(theta_true)))
    print(
        f"  check: -log_post(blind MAP) = {map_res.neg_log_posterior:.1f} vs "
        f"-log_post(truth) = {nlp_true:.1f}  "
        f"(MAP - truth = {map_res.neg_log_posterior - nlp_true:+.1f})"
    )
    with open(outdir / "map.json", "w") as f:
        json.dump(
            {
                "theta_map": np.asarray(theta_map).tolist(),
                "neg_log_posterior": map_res.neg_log_posterior,
                "neg_log_posterior_truth": nlp_true,
                "n_steps_per_start": map_res.n_steps,
                "archetypes": ARCHETYPES,
                **_phys_record(model, theta_map),
            },
            f,
            indent=2,
        )

    result = run_sampler(fwd, theta_map, args)

    # ---- break label symmetry: compact component first in every sample ----
    samples_ordered = jax.vmap(model.order_components_by_size)(result.samples)
    result_ordered = dataclasses.replace(result, samples=samples_ordered)
    result_ordered.to_hdf5(outdir / "posterior.hdf5")
    print(f"  Saved posterior: {outdir / 'posterior.hdf5'}")

    # ---- report ----
    dec = report_recovery(model, samples_ordered, theta_true, theta_map)
    theta_median = jnp.median(samples_ordered, axis=0)
    print("\n  Reduced chi2 (photon noise only, N_data - n_params dof):")
    print(f"    truth            {reduced_chi2(fwd, theta_true, variance):.4f}")
    print(f"    blind MAP        {reduced_chi2(fwd, theta_map, variance):.4f}")
    print(f"    posterior median {reduced_chi2(fwd, theta_median, variance):.4f}")
    if isinstance(result, NSSResult):
        print(
            f"  NSS: logZ = {result.logZ:.2f} +/- {result.logZ_err:.2f}, ESS = {result.ess:.0f}, "
            f"n_steps = {result.n_steps}"
        )

    # ---- figures ----
    print("\n--- Figures ---")
    plt = _setup_mpl()
    model_median_image = np.asarray(fwd._model_image(theta_median))
    plot_truth_model_residual(plt, figdir, true_image, flux_noisy, variance, model_median_image)
    plot_sps_param_maps(plt, figdir, model, result_ordered, theta_true)
    plot_sed_bulge_disk(
        plt, figdir, fwd, true_image, flux_noisy, variance, model_median_image, samples_ordered
    )
    plot_posterior_summary_1d(plt, figdir, model, dec)
    plot_sampler_diagnostics(plt, figdir, result, args.sampler)
    plot_component_profiles(plt, figdir, fwd, model, emulator, theta_true, theta_map, sigma)

    print(f"\nAll done in {time.perf_counter() - t_start:.0f}s. Outputs in: {outdir}")


if __name__ == "__main__":
    main()
