#!/usr/bin/env python3
"""Train the SPSMLPEmulator and fit the mock JWST dataset with arachne.

Steps
-----
1. **Train emulator** — load ``outputs/mock_data/training_library.h5`` and train
   a ``SPSMLPEmulator`` on the 5-band NIRCam photometry library generated by
   ``generate_mock_jwst.py``.  The trained model is saved to
   ``outputs/mock_data/emulator.eqx``.

2. **Regenerate mock** — re-run ``generate_mock_jwst.make_mock_images()`` now
   that a real emulator is available, so the FITS files are produced with the
   full forward model rather than the analytic proxy.

3. **Load observations** — read the per-band FITS files into an
   ``ObservationCube`` and per-band PSF FITS files into a ``PSFModel``.

4. **Build forward model** — assemble ``GaussianMixtureSpatialModel`` (K=2),
   ``PSFConvolver``, and ``ForwardModel``.

5. **Run NUTS** — initialise near the truth and run ``NUTSSampler`` for a short
   chain (demonstrating gradient-based inference end-to-end).

6. **Compare to truth** — print parameter recovery summary and save samples to
   ``outputs/mock_data/samples.hdf5``.

Usage
-----
    python scripts/fit_mock_jwst.py

Prerequisites
-------------
    python scripts/generate_mock_jwst.py   # generates training_library.h5
"""

from __future__ import annotations

import json
from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np

OUTDIR = Path("outputs/mock_data")

FILTER_CODES = [
    "JWST/NIRCam.F115W",
    "JWST/NIRCam.F150W",
    "JWST/NIRCam.F200W",
    "JWST/NIRCam.F277W",
    "JWST/NIRCam.F356W",
]
N_BANDS = len(FILTER_CODES)
SPS_PARAM_NAMES = ["log_stellar_mass", "log_age", "log_metallicity", "tau_v"]
PARAM_BOUNDS = {
    "log_stellar_mass": (5.0, 11.0),
    "log_age": (7.0, 10.3),
    "log_metallicity": (-3.0, 0.5),
    "tau_v": (0.0, 3.0),
}
PIXEL_SCALE = 0.031
NPIX = 32


# ---------------------------------------------------------------------------
# Step 1: Train emulator
# ---------------------------------------------------------------------------


def train_emulator():
    """Train SPSMLPEmulator on the BPASS training library."""
    from arachne.emulator.jax_mlp_emulator import SPSMLPEmulator

    lib_path = OUTDIR / "training_library.h5"
    emu_path = OUTDIR / "emulator.eqx"

    if emu_path.exists():
        print(f"\n--- Step 1: Loading existing emulator from {emu_path} ---")
        return SPSMLPEmulator.load(
            emu_path, param_names=SPS_PARAM_NAMES, band_names=FILTER_CODES
        )

    print(f"\n--- Step 1: Training SPSMLPEmulator ({lib_path}) ---")
    emulator = SPSMLPEmulator.from_synference_library(
        library_path=lib_path,
        param_names=SPS_PARAM_NAMES,
        band_names=FILTER_CODES,
        hidden_sizes=[256, 256, 256],
        n_epochs=500,
        batch_size=256,
        learning_rate=3e-4,
        val_fraction=0.1,
        seed=0,
        log_interval=50,
    )
    emulator.save(emu_path)
    print(f"  Saved emulator: {emu_path}")
    return emulator


# ---------------------------------------------------------------------------
# Step 2: Regenerate mock FITS with real emulator
# ---------------------------------------------------------------------------


def regenerate_mock(emulator) -> None:
    """Overwrite the analytic-proxy FITS with the real forward-model mock."""
    # Import and call the mock generation from the companion script
    import sys
    sys.path.insert(0, str(Path(__file__).parent))
    import generate_mock_jwst as gen

    # Temporarily inject the trained emulator by saving it where the script expects it
    emu_path = OUTDIR / "emulator.eqx"
    if not emu_path.exists():
        emulator.save(str(emu_path))

    print("\n--- Step 2: Regenerating mock FITS with real emulator ---")
    gen.make_mock_images()


# ---------------------------------------------------------------------------
# Step 3 & 4: Load data + build forward model
# ---------------------------------------------------------------------------


def load_observations():
    """Load per-band FITS files into ObservationCube."""
    from arachne.data.observation import ObservationCube

    flux_paths, var_paths = [], []
    for band in FILTER_CODES:
        safe = band.replace("/", "_").replace(".", "_")
        flux_paths.append(str(OUTDIR / f"{safe}_sci.fits"))
        var_paths.append(str(OUTDIR / f"{safe}_var.fits"))

    obs = ObservationCube.from_fits(
        flux_paths=flux_paths,
        variance_paths=var_paths,
        band_names=FILTER_CODES,
        pixel_scale=PIXEL_SCALE,
    )
    print("\n--- Step 3: Observation ---")
    print(f"  Shape: {obs.flux.shape}  ({obs.n_bands} bands, {obs.image_shape} pix)")
    print(f"  Flux range: [{obs.flux.min():.1f}, {obs.flux.max():.1f}] nJy")
    return obs


def load_psf_model():
    """Load PSF FITS files into PSFModel."""
    from arachne.data.psf import PSFModel

    psf_paths = {}
    for band in FILTER_CODES:
        safe = band.replace("/", "_").replace(".", "_")
        psf_paths[band] = str(OUTDIR / f"{safe}_psf.fits")
    return PSFModel.from_fits(psf_paths)


def build_forward_model(obs, psf_model, emulator):
    """Assemble ForwardModel with K=2 GMM spatial model."""
    from arachne.forward_model.pipeline import ForwardModel
    from arachne.spatial.gmm import GaussianMixtureSpatialModel

    spatial_model = GaussianMixtureSpatialModel(
        n_components=2,
        sps_param_names=SPS_PARAM_NAMES,
        param_bounds=PARAM_BOUNDS,
        image_shape=(NPIX, NPIX),
    )
    print("\n--- Step 4: Forward model ---")
    print(f"  Spatial model: K=2 GMM, {spatial_model.n_params} free params")

    fwd = ForwardModel.build(obs=obs, psf_model=psf_model,
                             spatial_model=spatial_model, emulator=emulator)

    # Quick sanity check: log_posterior is finite at theta=0
    theta0 = jnp.zeros(spatial_model.n_params)
    lp = fwd.log_posterior(theta0)
    print(f"  log_posterior(zeros) = {float(lp):.2f}  (should be finite)")
    assert jnp.isfinite(lp), "log_posterior is not finite at theta=0!"

    # Check gradient flows
    grad = jax.grad(fwd.log_posterior)(theta0)
    print(f"  grad norm at zeros: {float(jnp.linalg.norm(grad)):.2f}")
    return fwd, spatial_model


# ---------------------------------------------------------------------------
# Step 5: NUTS sampling
# ---------------------------------------------------------------------------


def run_nuts(fwd, spatial_model, theta_true: np.ndarray):
    """Run NUTSSampler, initialised near the truth."""
    from arachne.inference.nuts_sampler import NUTSSampler

    print("\n--- Step 5: NUTS sampling ---")

    # Initialise with small perturbation around truth
    rng = np.random.default_rng(1)
    theta_init = jnp.array(
        theta_true + rng.normal(0, 0.1, size=theta_true.shape), dtype=jnp.float32
    )

    sampler = NUTSSampler(
        forward_model=fwd,
        n_warmup=200,
        n_samples=300,
    )

    rng_key = jax.random.PRNGKey(42)
    result = sampler.run(theta_init, rng_key=rng_key)
    samples = np.array(result.samples)
    print(f"  Samples shape: {samples.shape}  (n_samples × n_params)")
    if result.acceptance_rate is not None:
        print(f"  Mean acceptance rate: {result.acceptance_rate:.3f}")

    # Save using built-in method
    samples_path = OUTDIR / "samples.hdf5"
    result.to_hdf5(samples_path)
    print(f"  Saved samples: {samples_path}")
    return samples


# ---------------------------------------------------------------------------
# Step 6: Parameter recovery
# ---------------------------------------------------------------------------


def report_recovery(samples, spatial_model, theta_true: np.ndarray):
    """Decode posterior samples and compare to truth SPS parameters."""
    print("\n--- Step 6: Parameter recovery ---")

    n_samples = samples.shape[0]
    K = spatial_model.n_components
    N_sps = len(SPS_PARAM_NAMES)
    params_per_comp = 5 + N_sps  # mu_y, mu_x, log_sig_y, log_sig_x, atanh_rho + sps

    # Decode each sample's SPS parameters for each component
    lo = np.array([PARAM_BOUNDS[p][0] for p in SPS_PARAM_NAMES])
    hi = np.array([PARAM_BOUNDS[p][1] for p in SPS_PARAM_NAMES])

    def decode_sps(theta_flat):
        theta_k = theta_flat.reshape(K, params_per_comp)
        sps_raw = theta_k[:, 5:]  # (K, N_sps)
        return lo + (hi - lo) * jax.nn.sigmoid(sps_raw)  # (K, N_sps)

    decoded_samples = np.array(jax.vmap(decode_sps)(samples))  # (n_samples, K, N_sps)
    truth_sps = decode_sps(theta_true)  # (K, N_sps)

    component_names = ["bulge (comp 0)", "disk (comp 1)"]
    for k, cname in enumerate(component_names):
        print(f"\n  {cname}:")
        for j, pname in enumerate(SPS_PARAM_NAMES):
            med = np.median(decoded_samples[:, k, j])
            lo16 = np.percentile(decoded_samples[:, k, j], 16)
            hi84 = np.percentile(decoded_samples[:, k, j], 84)
            truth_val = float(truth_sps[k, j])
            print(f"    {pname:20s}: truth={truth_val:7.3f}  "
                  f"recovered={med:7.3f} +{hi84-med:.3f} -{med-lo16:.3f}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main():
    lib_path = OUTDIR / "training_library.h5"
    if not lib_path.exists():
        raise FileNotFoundError(
            f"Training library not found at {lib_path}. "
            "Run: python scripts/generate_mock_jwst.py first."
        )

    # Step 1
    emulator = train_emulator()

    # Step 2: regenerate mock FITS with real emulator (no-op if FITS already have real data)
    sci_path = OUTDIR / f"{FILTER_CODES[0].replace('/','_').replace('.','_')}_sci.fits"
    if not sci_path.exists():
        regenerate_mock(emulator)
    else:
        # Always regenerate to ensure the mock uses the real emulator
        regenerate_mock(emulator)

    # Step 3
    obs = load_observations()

    # Step 4
    psf_model = load_psf_model()
    fwd, spatial_model = build_forward_model(obs, psf_model, emulator)

    # Load truth
    with open(OUTDIR / "true_params.json") as f:
        truth_dict = json.load(f)
    theta_true = np.array(truth_dict["theta_true"], dtype=np.float32)

    # Step 5
    samples = run_nuts(fwd, spatial_model, theta_true)

    # Step 6
    report_recovery(samples, spatial_model, theta_true)

    print("\nAll done. Outputs in:", OUTDIR)


if __name__ == "__main__":
    main()
