#!/usr/bin/env python3
"""Train the toy SPSMLPEmulator and fit the mock JWST dataset blind with arachne.

Steps
-----
1. **Train emulator** -- load ``outputs/mock_data/training_library.h5`` and train
   a ``SPSMLPEmulator`` on the 5-band NIRCam photometry library generated by
   ``generate_mock_jwst.py``.  The trained model is saved to
   ``outputs/mock_data/emulator.eqx``.

2. **Regenerate mock** -- re-run ``generate_mock_jwst.make_mock_images()`` now
   that a real emulator is available, so the FITS files are produced with the
   full forward model (``AdditiveComponentModel`` K=2 + PSF) rather than the
   analytic placeholder.

3. **Load observations** -- read the per-band FITS files into an
   ``ObservationCube`` and per-band PSF FITS files into a ``PSFModel``.

4. **Build forward model** -- ``AdditiveComponentModel`` (K=2: each component a
   unit-sum Gaussian light profile times the emulator SED of its own
   parameters, including its own total stellar mass), ``PSFConvolver``,
   ``ForwardModel``.

5. **Blind initialisation + MAP** -- ``blind_initial_theta`` (image moments +
   neutral SPS values; no truth information) followed by ``find_map`` (Adam
   with the component masses re-solved by linear least squares between
   rounds).

6. **Run NUTS** from the blind MAP.

7. **Compare to truth** -- print the parameter-recovery table (truth is used
   here only) and save samples to ``outputs/mock_data/samples.hdf5``.

Usage
-----
    python scripts/fit_mock_jwst.py            # GPU node recommended

Prerequisites
-------------
    python scripts/generate_mock_jwst.py       # generates training_library.h5
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))

import generate_mock_jwst as gen  # noqa: E402
from generate_mock_jwst import (  # noqa: E402
    EMULATOR_HIDDEN,
    FILTER_CODES,
    OUTDIR,
    PIXEL_SCALE,
    SPS_PARAM_NAMES,
    safe_band,
)

COMPONENT_NAMES = ["bulge (compact, comp 0)", "disk (extended, comp 1)"]
SHAPE_NAMES = ["mu_y [px]", "mu_x [px]", "sigma_y [px]", "sigma_x [px]", "rho"]


# ---------------------------------------------------------------------------
# Step 1: Train emulator
# ---------------------------------------------------------------------------


def train_emulator():
    """Train SPSMLPEmulator on the BPASS training library (or load a saved one)."""
    from arachne.emulator.jax_mlp_emulator import SPSMLPEmulator

    lib_path = OUTDIR / "training_library.h5"
    emu_path = OUTDIR / "emulator.eqx"

    if emu_path.exists():
        print(f"\n--- Step 1: Loading existing emulator from {emu_path} ---")
        return SPSMLPEmulator.load(
            emu_path,
            param_names=SPS_PARAM_NAMES,
            band_names=FILTER_CODES,
            hidden_sizes=EMULATOR_HIDDEN,
        )

    print(f"\n--- Step 1: Training SPSMLPEmulator ({lib_path}) ---")
    emulator = SPSMLPEmulator.from_synference_library(
        library_path=lib_path,
        param_names=SPS_PARAM_NAMES,
        band_names=FILTER_CODES,
        hidden_sizes=EMULATOR_HIDDEN,
        n_epochs=500,
        batch_size=256,
        learning_rate=3e-4,
        val_fraction=0.1,
        seed=0,
        log_interval=50,
    )
    emulator.save(emu_path)
    print(f"  Saved emulator: {emu_path}")
    return emulator


# ---------------------------------------------------------------------------
# Step 3 & 4: Load data + build forward model
# ---------------------------------------------------------------------------


def load_observations():
    """Load per-band FITS files into ObservationCube."""
    from arachne.data.observation import ObservationCube

    flux_paths = [str(OUTDIR / f"{safe_band(b)}_sci.fits") for b in FILTER_CODES]
    var_paths = [str(OUTDIR / f"{safe_band(b)}_var.fits") for b in FILTER_CODES]
    obs = ObservationCube.from_fits(
        flux_paths=flux_paths,
        variance_paths=var_paths,
        band_names=FILTER_CODES,
        pixel_scale=PIXEL_SCALE,
    )
    print("\n--- Step 3: Observation ---")
    print(f"  Shape: {obs.flux.shape}  ({obs.n_bands} bands, {obs.image_shape} pix)")
    print(f"  Flux range: [{obs.flux.min():.1f}, {obs.flux.max():.1f}] nJy")
    return obs


def load_psf_model():
    """Load PSF FITS files into PSFModel."""
    from arachne.data.psf import PSFModel

    return PSFModel.from_fits({b: str(OUTDIR / f"{safe_band(b)}_psf.fits") for b in FILTER_CODES})


def build_forward_model(obs, psf_model, emulator):
    """Assemble ForwardModel with the K=2 AdditiveComponentModel."""
    from arachne.forward_model.pipeline import ForwardModel

    spatial_model = gen.build_spatial_model()
    print("\n--- Step 4: Forward model ---")
    print(
        f"  Spatial model: AdditiveComponentModel K=2, {spatial_model.n_params} free params "
        f"(mass_param={spatial_model.mass_param!r}, component totals)"
    )
    fwd = ForwardModel.build(
        obs=obs, psf_model=psf_model, spatial_model=spatial_model, emulator=emulator
    )

    # Sanity check: log_posterior and its gradient are finite at a prior draw.
    theta0 = spatial_model.sample_prior(jax.random.PRNGKey(0), 1)[0]
    lp = fwd.log_posterior(theta0)
    grad = jax.grad(fwd.log_posterior)(theta0)
    gnorm = float(jnp.linalg.norm(grad))
    print(f"  log_posterior(prior draw) = {float(lp):.2f}, |grad| = {gnorm:.2f}")
    assert jnp.isfinite(lp) and jnp.all(jnp.isfinite(grad))
    return fwd, spatial_model


# ---------------------------------------------------------------------------
# Step 5 & 6: Blind MAP, then NUTS
# ---------------------------------------------------------------------------


def run_blind_map(fwd):
    """Blind MAP from the data alone (no truth information enters this function)."""
    from arachne.inference.initialisation import blind_initial_theta, find_map

    print("\n--- Step 5: Blind initialisation + MAP ---")
    t0 = time.perf_counter()
    theta0 = blind_initial_theta(fwd.spatial_model, fwd.observation)
    print(f"  -log_post(blind start) = {-float(fwd.log_posterior(theta0)):.1f}")
    # The toy MLP emulator is not exactly linear in 10**log_stellar_mass, so the
    # linear mass solve inside find_map is only an initialiser here; the Adam
    # rounds correct the residual nonlinearity.
    res = find_map(fwd, theta0)
    print(
        f"  blind MAP: -log_post = {res.neg_log_posterior:.1f} after {res.n_steps} steps "
        f"[{time.perf_counter() - t0:.0f}s]"
    )
    return res


def run_nuts(fwd, theta_init, n_warmup: int = 300, n_samples: int = 500):
    """Run NUTSSampler from the blind MAP."""
    from arachne.inference.nuts_sampler import NUTSSampler

    print(f"\n--- Step 6: NUTS ({n_warmup} warmup + {n_samples} samples) from the blind MAP ---")
    t0 = time.perf_counter()
    sampler = NUTSSampler(fwd, n_warmup=n_warmup, n_samples=n_samples, max_num_doublings=10)
    result = sampler.run(jnp.asarray(theta_init, dtype=jnp.float32), jax.random.PRNGKey(42))
    infos = result.infos
    samples = np.asarray(result.samples)
    print(
        f"  acceptance = {result.acceptance_rate:.3f}   "
        f"mean tree depth = {float(np.mean(np.asarray(infos.num_trajectory_expansions))):.1f}   "
        f"divergences = {int(np.sum(np.asarray(infos.is_divergent)))}   "
        f"fraction of dims that moved = {float(np.mean(samples.std(axis=0) > 0)):.2f}   "
        f"[{time.perf_counter() - t0:.0f}s]"
    )
    # Components are exchangeable: order compact-first in every sample.
    ordered = jax.vmap(fwd.spatial_model.order_components_by_size)(result.samples)
    result.samples = ordered
    samples_path = OUTDIR / "samples.hdf5"
    result.to_hdf5(samples_path)
    print(f"  Saved samples: {samples_path}")
    return ordered


# ---------------------------------------------------------------------------
# Step 7: Parameter recovery
# ---------------------------------------------------------------------------


def _decode(spatial_model, thetas):
    free_cols = jnp.array(
        [spatial_model.emulator_param_names.index(p) for p in spatial_model.sps_param_names]
    )

    def one(theta):
        mu, sigma, rho, sps = spatial_model.component_params(theta)
        return sps[:, free_cols], jnp.concatenate([mu, sigma, rho[:, None]], axis=1)

    sps, shape = jax.vmap(one)(jnp.atleast_2d(jnp.asarray(thetas, dtype=jnp.float32)))
    return np.asarray(sps), np.asarray(shape)


def report_recovery(samples, spatial_model, theta_true: np.ndarray, theta_map) -> None:
    """Decode posterior samples and compare to the truth (truth used here only)."""
    print("\n--- Step 7: Parameter recovery (truth used for grading only) ---")
    sps, shape = _decode(spatial_model, samples)
    sps_t, shape_t = _decode(spatial_model, theta_true)
    sps_m, shape_m = _decode(spatial_model, theta_map)
    n68 = n95 = n = 0
    for k, cname in enumerate(COMPONENT_NAMES):
        print(f"\n  {cname}:")
        rows = [
            (p, sps[:, k, j], sps_t[0, k, j], sps_m[0, k, j]) for j, p in enumerate(SPS_PARAM_NAMES)
        ]
        rows += [
            (s, shape[:, k, j], shape_t[0, k, j], shape_m[0, k, j])
            for j, s in enumerate(SHAPE_NAMES)
        ]
        for name, x, truth, mapv in rows:
            q2, q16, q50, q84, q97 = np.percentile(x, [2.5, 16, 50, 84, 97.5])
            in68 = q16 <= truth <= q84
            in95 = q2 <= truth <= q97
            dev = abs(q50 - truth) / max(0.5 * (q84 - q16), 1e-12)
            print(
                f"    {name:18s} truth={truth:8.3f}  median={q50:8.3f} [{q16:8.3f},{q84:8.3f}]  "
                f"in68={'yes' if in68 else ' no'}  |med-truth|/halfwidth={dev:6.2f}  "
                f"MAP={mapv:8.3f}"
            )
            n68 += in68
            n95 += in95
            n += 1
    mi = spatial_model.mass_index
    tot = np.log10(np.sum(10.0 ** sps[:, :, mi], axis=1))
    tot_t = np.log10(np.sum(10.0 ** sps_t[0, :, mi]))
    q16, q50, q84 = np.percentile(tot, [16, 50, 84])
    print(f"\n  total log10 M*: truth={tot_t:.3f}  median={q50:.3f} [{q16:.3f},{q84:.3f}]")
    print(f"  Summary: truth inside 68% interval {n68}/{n}, inside 95% {n95}/{n}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main():
    """Entry point: train emulator, regenerate mock, blind MAP, NUTS, report."""
    lib_path = OUTDIR / "training_library.h5"
    if not lib_path.exists():
        raise SystemExit(
            f"Training library not found at {lib_path}. "
            "Run: python scripts/generate_mock_jwst.py first."
        )
    print(f"JAX backend: {jax.default_backend()}")

    emulator = train_emulator()

    # Always regenerate so the mock is produced by the trained emulator.
    print("\n--- Step 2: Regenerating mock FITS with the trained emulator ---")
    gen.make_mock_images()

    obs = load_observations()
    psf_model = load_psf_model()
    fwd, spatial_model = build_forward_model(obs, psf_model, emulator)

    map_res = run_blind_map(fwd)
    samples = run_nuts(fwd, map_res.theta)

    # Truth enters only from here on, for grading.
    with open(OUTDIR / "true_params.json") as f:
        theta_true = np.array(json.load(f)["theta_true"], dtype=np.float32)
    print(
        f"  check: -log_post(blind MAP) = {map_res.neg_log_posterior:.1f} vs "
        f"-log_post(truth) = {-float(fwd.log_posterior(jnp.asarray(theta_true))):.1f}"
    )
    report_recovery(samples, spatial_model, theta_true, map_res.theta)

    print("\nAll done. Outputs in:", OUTDIR)


if __name__ == "__main__":
    main()
